apiVersion: apps/v1
kind: Deployment
metadata:
  name: databutton
spec:
  replicas: 1
  template:
    spec:
      containers:
      - args:
        - .databutton/app/tmp-f4d13975-79a9-f1ce-3bad-38332495a063.py
        - --server.port
        - '8501'
        - --server.address=0.0.0.0
        - --server.fileWatcherType=none
        - --server.enableWebsocketCompression=true
        - --browser.gatherUsageStats=false
        - --global.dataFrameSerialization=arrow
        - --server.headless=true
        command:
        - streamlit
        - run
        env:
        - name: PYTHONPATH
          value: .
        envFrom: &id001
        - secretRef:
            name: databutton-secret
        image: databutton-base
        imagePullPolicy: IfNotPresent
        livenessProbe: &id002
          httpGet:
            path: /
            port: http
        name: route-f4d13975-79a9-f1ce-3bad-38332495a063
        ports:
        - containerPort: 8501
          name: http
        readinessProbe: &id003
          httpGet:
            path: /
            port: http
        resources:
          limits:
            cpu: '0.2'
            memory: 256Mi
          requests:
            cpu: '0.2'
            memory: 256Mi
      - command:
        - databutton
        - schedule
        env:
        - name: PYTHONPATH
          value: .
        envFrom: *id001
        image: databutton-base
        imagePullPolicy: IfNotPresent
        name: scheduler
        resources:
          limits:
            cpu: '1'
            memory: 2056Mi
          requests:
            cpu: '1'
            memory: 2056Mi
      - command:
        - databutton
        - serve
        env:
        - name: PYTHONPATH
          value: .
        envFrom: *id001
        image: databutton-base
        imagePullPolicy: IfNotPresent
        livenessProbe: *id002
        name: main
        ports:
        - containerPort: 8000
          name: http
        readinessProbe: *id003
        resources:
          limits:
            cpu: '0.2'
            memory: 256Mi
          requests:
            cpu: '0.2'
            memory: 256Mi
